#! /bin/sh

current=`git branch | sed -n '/^\* /s///p'`
non_master=`git branch | sed -e '/ master$/d' -e 's/^\* //'`

for branch in $non_master; do
  git checkout $branch
  git merge master
done
git checkout $current


