#! /bin/sh

current=`git-branch | sed -n '/^\* /s//p'`
non_master=`git-branch | sed -n '!/ master$/s/^\* //p'

for branch in $non_master; do
  echo git checkout $branch
  echo git merge master
done
 echo git checkout $current


