#! /bin/sh

########################################################################
reconf () {
  path=$1
  shift
  sfx=$1
  shift
  pwd=`pwd`
  build=$pwd/_build$sfx
  inst=$pwd/_inst$sfx
  ( PATH=$path
    export PATH
    rm -fr $inst
    mkdir $inst
    rm -fr $build
    mkdir $build
    cd $build
    ../configure --prefix=$inst "$@"
  )
}

########################################################################
autoreconf
reconf $PATH ""
reconf /home/ohl/ml/4.02/bin:$PATH _402
reconf $PATH _mf --enable-distribution --enable-model-files



