#! /bin/sh
# update -- generate fresh Makefile.depend etc.
# $Id: update 4015 2013-01-03 16:04:18Z jr_reuter $
########################################################################
#
# Copyright (C) 1999-2013 by 
#     Wolfgang Kilian <kilian@physik.uni-siegen.de>
#     Thorsten Ohl <ohl@physik.uni-wuerzburg.de>
#     Juergen Reuter <juergen.reuter@desy.de>
#     Christian Speckner <cnspeckn@googlemail.com>
#
# WHIZARD is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# WHIZARD is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
########################################################################

########################################################################
#
# Syncing version tags with WHIZARD
#
########################################################################

configure_ac_parent=../../configure.ac
configure_ac=configure.ac
tmp=configure.ac.$$

if test -f "$configure_ac_parent"; then

  AC_INIT="`sed -n '/^AC_INIT/s/WHIZARD/omega/p' $configure_ac_parent`"
  AM_INIT_AUTOMAKE="`grep '^AM_INIT_AUTOMAKE' $configure_ac_parent`"
  AC_PREREQ="`grep '^AC_PREREQ' $configure_ac_parent`"
  LT_PREREQ="`grep '^LT_PREREQ' $configure_ac_parent`"

  sed \
    -e "/^AC_INIT/s/^.*\$/$AC_INIT/" \
    -e "/^AM_INIT_AUTOMAKE/s/^.*\$/$AM_INIT_AUTOMAKE/" \
    -e "/^AC_PREREQ/s/^.*\$/$AC_PREREQ/" \
    -e "/^LT_PREREQ/s/^.*\$/$LT_PREREQ/" $configure_ac > $tmp

  if cmp -s -- $tmp $configure_ac; then
    rm $tmp
  else
    mv $tmp $configure_ac
  fi

fi

########################################################################
#
# Syncing files with the WHIZARD
#
########################################################################

inherit_files () {
  while read whizard omega; do
    if test -f "$whizard"; then
      if test "$whizard" -nt "$omega"; then
        cp -- "$whizard" "$omega"
      elif test "$omega" -nt "$whizard" && ! cmp -s -- "$omega" "$whizard"; then
        echo "$omega" newer than "$whizard": consider "diff -u $whizard $omega"
      fi
    fi
  done
}

inherit_files <<EOF
  ../../---README_1st_SVN--- ---README_1st_SVN---
  ../../AUTHORS         AUTHORS
  ../../COPYING         COPYING
  ../../config.guess    config.guess
  ../../config.sub      config.sub
  ../../install-sh      install-sh
  ../../ltmain.sh       ltmain.sh
  ../../test-driver     test-driver
  ../../aux.m4          m4/aux.m4
  ../../m4/fortran.m4   m4/fortran.m4
  ../../m4/latex.m4     m4/latex.m4
  ../../m4/libtool.m4   m4/libtool.m4
  ../../m4/ltversion.m4 m4/ltversion.m4
  ../../m4/ltoptions.m4 m4/ltoptions.m4
  ../../m4/ltsugar.m4   m4/ltsugar.m4 
  ../../m4/ltdl.m4      m4/ltdl.m4 
  ../../m4/noweb.m4     m4/noweb.m4
  ../../m4/ocaml.m4     m4/ocaml.m4
  ../../missing         missing
  ../../depcomp         depcomp
  ../misc/constants.f90 src/constants.f90
  ../misc/kinds.f90.in  src/kinds.f90.in
  ../../share/doc/noweb.sty share/doc/noweb.sty
  ../../share/doc/thophys.sty share/doc/thophys.sty
EOF
