#! /bin/sh
########################################################################

jobs=
jobs="-j 6"

make -C ../_build_mf/src $jobs || exit 0
make -C ../_build_mf/tests vertex_unit $jobs || exit 0
( ln -f ../tests/omf.sty \
        ../tests/QCD.omf ../tests/QCD.tex \
        ../tests/SM.omf ../tests/SM.tex \
    ../_build_mf/tests/
  cd ../_build_mf/tests
  ./vertex_unit "$@"
  # pdflatex -halt-on-error QCD
  # pdflatex -halt-on-error SM
)
  

