#! /bin/sh
########################################################################

jobs="-j 6"

make -C ../_build_mf/src $jobs || exit 0
make -C ../_build_mf/tests vertex_unit $jobs || exit 0
exec ../_build_mf/tests/vertex_unit "$@"

