#! /bin/sh
# update -- autotools files
# $Id: update 2553 2010-05-21 11:36:05Z jr_reuter $
########################################################################
#
# Copyright (C) 1999-2014 by 
#     Wolfgang Kilian <kilian@physik.uni-siegen.de>
#     Thorsten Ohl <ohl@physik.uni-wuerzburg.de>
#     Juergen Reuter <juergen.reuter@desy.de>
#     with contributions from
#     Christian Speckner <cnspeckn@googlemail.com>
#
# WHIZARD is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by 
# the Free Software Foundation; either version 2, or (at your option)
# any later version.
#
# WHIZARD is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
########################################################################

########################################################################
#
# Syncing version tags with WHIZARD
#
########################################################################

configure_ac_parent=../configure.ac
configure_ac=configure.ac
tmp=configure.ac.$$

if test -f "$configure_ac_parent"; then

  AC_INIT="`sed -n '/^AC_INIT/s/WHIZARD/circe1/p' $configure_ac_parent`"
  AM_INIT_AUTOMAKE="`grep '^AM_INIT_AUTOMAKE' $configure_ac_parent`"
  AC_PREREQ="`grep '^AC_PREREQ' $configure_ac_parent`"
  LT_PREREQ="`grep '^LT_PREREQ' $configure_ac_parent`"

  sed \
    -e "/^AC_INIT/s/^.*\$/$AC_INIT/" \
    -e "/^AM_INIT_AUTOMAKE/s/^.*\$/$AM_INIT_AUTOMAKE/" \
    -e "/^AC_PREREQ/s/^.*\$/$AC_PREREQ/" \
    -e "/^LT_PREREQ/s/^.*\$/$LT_PREREQ/" $configure_ac > $tmp

  if cmp -s -- $tmp $configure_ac; then
    rm $tmp
  else
    mv $tmp $configure_ac
  fi

fi

########################################################################
#
# Syncing files with the WHIZARD
#
########################################################################

inherit_files () {
  while read whizard circe1; do
    if test -f "$whizard"; then
      if test "$whizard" -nt "$circe1"; then
        cp -- "$whizard" "$circe1"
      elif test "$circe1" -nt "$whizard" && ! cmp -s -- "$circe1" "$whizard"; then
        echo "$circe1" newer than "$whizard": consider "diff -u $whizard $circe1"
      fi
    fi
  done
}

inherit_files <<EOF
  ../---README_1st_SVN--- ---README_1st_SVN---
  ../AUTHORS         AUTHORS
  ../COPYING         COPYING
  ../config.guess    config.guess
  ../config.sub      config.sub
  ../install-sh      install-sh
  ../ltmain.sh       ltmain.sh
  ../test-driver     test-driver
  ../missing         missing
  ../depcomp         depcomp
  ../compile         compile
  ../m4/aux.m4       m4/aux.m4
  ../m4/fortran.m4   m4/fortran.m4
  ../m4/latex.m4     m4/latex.m4
  ../m4/libtool.m4   m4/libtool.m4
  ../m4/ltversion.m4 m4/ltversion.m4
  ../m4/ltoptions.m4 m4/ltoptions.m4
  ../m4/ltsugar.m4   m4/ltsugar.m4 
  ../m4/ltdl.m4      m4/ltdl.m4 
  ../m4/noweb.m4     m4/noweb.m4
  ../src/basics/kinds.f90.in  src/kinds.f90.in
  ../share/doc/noweb.sty share/doc/noweb.sty
  ../share/doc/thophys.sty share/doc/thophys.sty
EOF

# ../src/misc/constants.f90 src/constants.f90
