stages:
  - autotools
  - configure
  - build
  - cleanup_build
  - test
  - deploy

whizard:
  stage: autotools
  script:
    - autoreconf
  stage: configure
  script:
    - ./configure FC=nagfor FCFLAGS="-C=all -gline -nan -f2008" --prefix="nagfor" --enable-distribution 
  stage: build
  script:
    - make 
