stages:
  - autotools
  - build
  - cleanup_build
  - test
  - deploy

autotools:
  stage: autotools
  script:
    - autoreconf
  artifacts:
    untracked: true

build:nagfor:
  stage: build
  script:
    - mkdir -p build.nagfor
    - cd build.nagfor
    - ../configure FC=nagfor FCFLAGS="-O0 -C=all -gline -nan -f2008" --prefix="`pwd`/../install.nagfor" --disable-static
    - make > make.log
  cache:
    paths:
      - build.nagfor/

build:gfortran:
  stage: build
  script:
    - mkdir -p build.gfortran
    - cd build.gfortran
    - ../configure FC=gfortran FCFLAGS="-O0" --prefix="`pwd`/../install.gfortran" --disable-static
    - make > make.log
  cache:
    paths:
      - build.gfortran/
