stages:
  - autotools
  - build
  - cleanup_build
  - test
  - deploy

autotools:
  stage: autotools
  script:
    - autoreconf
  artifacts:
    untracked: true

build:nagfor:
  stage: build
  script:
    - mkdir -p build.nagfor
    - cd build.nagfor
    - ../configure FC=nagfor FCFLAGS="-C=all -gline -nan -f2008" --prefix="`pwd`/../install.nagfor" --enable-distribution
    - make
  cache:
    paths:
      - build.nagfor/
