stages:
  - autotools
  - build
  - cleanup_build
  - test
  - deploy

autotools:
  stage: autotools
  script:
    - autoreconf
  artifacts:
    - configure

build:nagfor:
  stage: build
  script:
    - mkdir -p build.nagfor
    - cd build.nagfor
    - ../configure FC=nagfor FCFLAGS="-C=all -gline -nan -f2008" --prefix="nagfor" --enable-distribution
    - make 
