stages:
  - autotools
  - build
  - test
  - deploy

cleanup:
  script:
    - find . -type f -exec chmod 644 {} +
    - find . -type d -exec chmod 755 {} +
    - rm build* -rf
    - rm install* -rf
  when: manual

autotools:
  stage: autotools
  script:
    - autoreconf
  artifacts:
    untracked: true
    expire_in: 3 weeks

.build_template: &build_definition
  stage: build
  before_script:
    - mkdir -p "$CI_BUILD_NAME"
    - cd "$CI_BUILD_NAME"

build.nagfor:
  <<: *build_definition
  script:
    - ../configure FC=nagfor FCFLAGS="-O0 -C=all -gline -nan -f2008" --prefix="`pwd`/../install.nagfor" --disable-static > configure.log
    - make -s V=0 > make.log
    - make -s V=0 install > make-install.log
  artifacts:
    expire_in: 3 weeks
    paths:
      - build.nagfor/

build.gfortran:
  <<: *build_definition
  script:
    - ../configure FC=gfortran FCFLAGS="-O0" --prefix="`pwd`/../install.gfortran" --disable-static
    - make -s V=0 > make.log
    - make -s V=0 install > make-install.log
  artifacts:
    expire_in: 3 weeks
    paths:
      - build.gfortran/

.test_template: &test_definition
  stage: test
  before_script:
    - cd "${CI_BUILD_NAME/test/build}"
  script:
    - make -s V=0 check

.test_extra_template: &test_extra_definition
  <<: *build_definition
  <<: *test_definition
  only:
    - master

test.nagfor:
  <<: *test_definition
  dependencies:
    - build.nagfor

test.gfortran:
  <<: *test_definition
  dependencies:
    - build.gfortran

test.nagfor.distribution:
  <<: *test_extra_definition
  script:
    - ../configure FC=nagfor FCFLAGS="-O0 -C=all -gline -nan -f2008" --prefix="`pwd`/../install.nagfor.distribution" --enable-distribution
    - make -s V=0 > make.log
    - make -s V=0 install > make-install.log
    - make -s V=0 check
    - make -s V=0 distcheck > make.distcheck.log
    - make -s V=0 extra-distcheck > make.extra-distcheck.log

test.gfortran.distribution:
  <<: *test_extra_definition
  script:
    - ../configure FC=gfortran FCFLAGS="-O0" --prefix="`pwd`/../install.gfortran" --enable-distribution
    - make -s V=0 > make.log
    - make -s V=0 install > make-install.log
    - make -s V=0 check
    - make -s V=0 distcheck > make.distcheck.log
    - make -s V=0 extra-distcheck > make.extra-distcheck.log


deploy to production:
  stage: deploy
  environment: production
  only:
    - master
  script:
    - git push production HEAD:master
