verbose: false
instrumentation:
  root: .
  includes: ['helpers/*.js', 'controllers/*.js']
  excludes: ['node-modules/*', 'lib/*', 'webpack.config.js']
  include-all-sources: true
  es-modules: true
reporting:
  dir: ./test/coverage
hooks:
check:
