verbose: false
instrumentation:
  root: .
  includes: ['lib/*.js']
  excludes: ['src/*.js', 'node-modules/*', 'bootstrap.min.js']
  include-all-sources: true
  es-modules: true
reporting:
  dir: ./test/coverage
hooks:
check:
